# Generated by Django 5.0.7 on 2024-07-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='properties', through='service.Amenity', to='service.amenitytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.ManyToManyField(to='service.room'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amenity_properties', to='service.amenitytype'),
        ),
    ]
