# Generated by Django 5.0.7 on 2024-07-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_property_amenities_property_host_property_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.property'),
            preserve_default=False,
        ),
    ]
